### ISSUE TITLE
Decode on iam-htr experiment

### ISSUE THREAD

**Issue by manucarbonell** [jpuigcerver/PyLaia#20]
Hi, I trained the model from the iam-htr example, but when I try to run the decode script it gives the following error
```
./src/decode_net.sh 
ERROR: File "data/lang/lines/char/aachen/te.txt" does not exist!
```
I did solve this one changing the path with puigcerver partition te.txt file, but then comes another missing file error.
Do you have a running version of the decode part of the iam-htr example?
Thank you,
Manu

**Comment by kleopatramarkou** [comment]
I had the same problem, I changed the path to "data/lang/puigcerver/lines/char/te.txt" from the decode_net.sh. 
I don't know if this is the solution to our problem, because I had another afterwards (probably, they are not related :
WARNING: compute-wer-bootci was not found, so CER/WER won't be computed!)

**Comment by carmocca** [comment]
The files missing are supposed to get created during the `prepare_texts.sh` step of the process. However, some refactoring done to that script has left the `decode_net.sh` script outdated. @jpuigcerver Can you have a look at the changes?

@kleopatramarkou That is just a warning since those metrics are computed using the `compute-wer-bootci` [tool provided with Kaldi](https://kaldi-asr.org/doc/tools.html). Feel free to use an equivalent tool on the generated transcriptions.

**Comment by carmocca** [comment]
I ended up having a look myself. It should be fixed by 809d9d50ea9c44121d0a33a352dfb945122ad972.

Feel free to close this issue if the problem is solved.

**Comment by manucarbonell** [comment]
Now it does not give any path error and starts decoding, I get the following error though
`UnicodeDecodeError: 'ascii' codec can't decode byte 0xd7 in position 5: ordinal not in range(128)`

**Comment by carmocca** [comment]
Seems like the experiment checkpoint being loaded to start the decoding process has some encoding issue. Was it generated using the same machine? Or perhaps using Python 2?

**Comment by manucarbonell** [comment]
Possibly python 2, I will train and run again.

**Comment by manucarbonell** [comment]
It works after reinstalling pylaia making sure it runs everything with python3
